name: unittest-on-commit

on:
  pull_request:
    types: [synchronize]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.10'
        activate-environment: orbgen
        use-only-tar-bz2: true

    - name: Install prerequisite by conda
      run: |
        conda init
        conda activate orbgen
        conda install pytorch torchvision torchaudio cpuonly -c pytorch

    - name: Install the package
      run: |
        conda activate orbgen
        pip install -e .

    - name: Set up permissions for execute
      run: chmod +x ./.github/tests/xtest.sh

    - name: Run xtest.sh shell script
      run: |
        conda activate orbgen
        output=$(./.github/tests/xtest.sh)
        exit_code=$?
        echo "$output"
        if [ $exit_code -ne 0 ]; then
          echo "Tests failed with exit code $exit_code"
          exit $exit_code
        fi

