name: unittest-on-commit

on:
  pull_request:
    types: [synchronize]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up permissions for execute
      run: chmod +x ./SIAB/spillage/xtest.sh
      
    - name: Run xtest.sh shell script
      run: |
        output=$(./SIAB/spillage/xtest.sh)
        exit_code=$?
        echo "$output"
        if [ $exit_code -ne 0 ]; then
          echo "Tests failed with exit code $exit_code"
          exit $exit_code
        fi
      
